### PR TITLE
Fix the main section image and text height

### LINKED ISSUE #37: fix the main section image and text height

### PR DESCRIPTION
**Pull request by devtofunmi**
### What type of PR is this?

- [* ] bug
- [ ] feature
- [ ] documentation
- [ ] test

###  Description of changes made 

- adjust the width of the main section image
- adjust the leading of the main section h1 text

### What this PR fixes 

closes #37 
### added test?

- [* ] yes
- [ ] no

### screenshots( if neccessary ):
**for large views**

**for medium view**

**for small view**

### CODE REVIEW

**Comment by dev-phantom** [comment]
image

nice job 
but dont you think they are a little too big

**Comment by devtofunmi** [comment]
Thanks for the review,I will fix it.

**Comment by Praisecodes** [comment]
Great Job @devtofunmi 
I think the landing page could use a little work anyways.
The first text the user sees is too big in my opinion
image

Also the padding could use some work, try adjust the padding by reducing it on the header and also on the first text the user sees.

Going over to the second section, which is the about section.
On mobile view, it doesn't really look good. Here's what I mean:
image
You can add a little padding to this section, please.

**Comment by devtofunmi** [comment]
@Praisecodes  and @dev-phantom i have fix it.

**Pull request closed without merging**
